WITH FRONTEND_SKILLS AS(
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY = "Front End"
)

SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS JOIN FRONTEND_SKILLS ON SKILL_CODE & CODE
ORDER BY ID;